# Configuration for Signing of app
# `💡` Lifecycle folder contains composite workflows that are involved with the CI\CD lifecycle of chapchap such as signing of application code before deployment.

name: "Code sign android Application"
description: "Creates a github release the various builds of the app"
runs:
  using: "composite"
  steps:
    - name: Sign APK
      if: startsWith(github.ref, 'refs/tags/') && github.repository == 'WalterBanda/chapchap'
      uses: r0adkll/sign-android-release@v1
      with:
          releaseDirectory: app/build/outputs/apk/standard/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Clean up build artifacts
      if: startsWith(github.ref, 'refs/tags/') && github.repository == 'chapchaporg/chapchap'
      run: |
          set -e
          mv app/build/outputs/apk/standard/release/app-standard-universal-release-unsigned-signed.apk chapchap-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum chapchap-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV
          cp app/build/outputs/apk/standard/release/app-standard-arm64-v8a-release-unsigned-signed.apk chapchap-arm64-v8a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum chapchap-arm64-v8a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV
          cp app/build/outputs/apk/standard/release/app-standard-armeabi-v7a-release-unsigned-signed.apk chapchap-armeabi-v7a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum chapchap-armeabi-v7a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV
          cp app/build/outputs/apk/standard/release/app-standard-x86-release-unsigned-signed.apk chapchap-x86-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum chapchap-x86-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV
          
          cp app/build/outputs/apk/standard/release/app-standard-x86_64-release-unsigned-signed.apk chapchap-x86_64-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum chapchap-x86_64-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA=$sha" >> $GITHUB_ENV
