/// Flutter icons ChapChap
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ChapChap
///      fonts:
///       - asset: fonts/ChapChap.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ChapChap {
  ChapChap._();

  static const _kFontFam = 'ChapChap';
  static const String? _kFontPkg = null;

  static const IconData logo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dark = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caret_down = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData admin = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_filled = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf09a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xf0c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
