# Create Github release for app

name: "Release to Github"
description: "Creates a github release the various builds of the app"
runs:
  using: "composite"
  steps:
    - name: Get tag name
      if: startsWith(github.ref, 'refs/tags/') && github.repository == 'WalterBanda/chapchap-client'
      run: |
        set -x
        echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') && github.repository == 'WalterBanda/chapchap-client'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION_TAG }}
        name: ChapChap ${{ env.VERSION_TAG }}
        body: |
          ---
          ### Checksums
          | Variant | SHA-256 |
          | ------- | ------- |
          | Universal | ${{ env.APK_UNIVERSAL_SHA }}
          | arm64-v8a | ${{ env.APK_ARM64_V8Az_SHA }}
          | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
          | x86 | ${{ env.APK_X86_SHA }} |
          | x86_64 | ${{ env.APK_X86_64_SHA }} |
        files: |
          chapchap-${{ env.VERSION_TAG }}.apk
          chapchap-arm64-v8a-${{ env.VERSION_TAG }}.apk
          chapchap-armeabi-v7a-${{ env.VERSION_TAG }}.apk
          chapchap-x86-${{ env.VERSION_TAG }}.apk
          chapchap-x86_64-${{ env.VERSION_TAG }}.apk
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
