// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBi8XBgozJeTfGS-G50GnP7M_d0HfPLIk',
    appId: '1:687165872597:web:491aa7e0c4b24b4a89055c',
    messagingSenderId: '687165872597',
    projectId: 'chapchap-90547',
    authDomain: 'chapchap-90547.firebaseapp.com',
    storageBucket: 'chapchap-90547.appspot.com',
    measurementId: 'G-DQ1QZYFF66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG1TxCL4Djpegsiez_C5jQa7ymYE0CLEY',
    appId: '1:687165872597:android:11e2380f06a9003589055c',
    messagingSenderId: '687165872597',
    projectId: 'chapchap-90547',
    storageBucket: 'chapchap-90547.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBi8XBgozJeTfGS-G50GnP7M_d0HfPLIk',
    appId: '1:687165872597:web:09ac8fff0088ca9389055c',
    messagingSenderId: '687165872597',
    projectId: 'chapchap-90547',
    authDomain: 'chapchap-90547.firebaseapp.com',
    storageBucket: 'chapchap-90547.appspot.com',
    measurementId: 'G-0PT3KV58VL',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBBi8XBgozJeTfGS-G50GnP7M_d0HfPLIk',
    appId: '1:687165872597:web:6b75c5e0c68ea29989055c',
    messagingSenderId: '687165872597',
    projectId: 'chapchap-90547',
    authDomain: 'chapchap-90547.firebaseapp.com',
    storageBucket: 'chapchap-90547.appspot.com',
    measurementId: 'G-JX75CD5W34',
  );
}
