# TODO Update release workflow
name: Release for android
description: Workflow that signs the built apk and aab, deploys it to playstore

inputs:
  GOOGLE_SERVICE_ACCOUNT_KEY:
    description: Secret key for deploying apk to Google playstore
    required: true

runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Install Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: 307.0.0

    - name: Deploy to Google Play Store
      uses: GoogleCloudPlatform/github-actions/deploy-google-play-store@master
      with:
        service_account_key: ${{ inputs.GOOGLE_SERVICE_ACCOUNT_KEY }}
        release_notes_file: CHANGELOG.md
        track: internal
        apk_file: app/build/outputs/apk/release/app-release.apk
        app_bundle_file: app/build/outputs/bundle/release/app.aab
