name: Deploy built web Project
description: Workflow that deploys the project to firebase

inputs:
  github_token:
    required: true
    description: Token authorizing deploy from github.repository
  firebaseServiceAccount:
    required: true
    description: Token containing firebase service account for project
  production_channel:
    # Provide channel details when its a production deployment
    required: false
    description: Channel to deploy project to

runs:
  using: composite
  steps:
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ inputs.github_token }}
        firebaseServiceAccount: ${{ inputs.firebaseServiceAccount }}
        channelId: ${{ inputs.production_channel }}
        projectId: chapchap-90547
