name: Creates a Github release doc
description: Workflow that creates a download Github release with the various binaries when PR is merged

inputs:
  is_prod:
    description: Check whether its a release build then creates an app bundle build for release builds
    required: true
    default: "false"

  GITHUB_TOKEN:
    description: Token to authorize the creation of github release
    required: true

runs:
  using: composite
  steps:
    - name: Generate screenshot
      shell: bash
      run: |
        # Take a screenshot and save it in the `screenshots` directory
        make screenshot

    - name: Upload screenshot
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: screenshots/screenshot.png

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        draft: false
        prerelease: false
        body: |
          ## Changes
          - Fixed a bug
          - Added a new feature

          ## Screenshot
          ![Screenshot](screenshots/screenshot.png)

          ## Download
          [Download the APK files](https://github.com/{OWNER}/{REPO}/releases/download/v1.0.0/apk.zip)
