name: Creates a Github release doc
description: Workflow that creates a download Github release with the various binaries when PR is merged

inputs:
  is_prod:
    description: Check whether its a release build then creates an app bundle build for release builds
    required: true
    default: "false"

runs:
  using: composite
  steps:
    - name: Build an APK all targets
      if: ${{inputs.is_prod == "true"}}
      run: flutter build apk
      shell: bash
    - name: Build an APK and splits them for all targets
      if: ${{inputs.is_prod == "true"}}
      run: flutter build apk --split-per-abi
      shell: bash
    - name: Build an APK all targets, splitting is playstores job
      if: ${{inputs.is_prod == "true"}}
      run: flutter build appbundle
      shell: bash
