# Runs when a PR is merged or production bug is fixed.

name: Release workflow

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - develop

jobs:
  project_setup_testing:
    name: Setup and testing of the Project
    runs-on: ubuntu-latest
    steps:
      # Setup environment for building and testing.
      - name: Project setup + Flutter SDK setup
        uses: WalterBanda/chapchap-client/.github/actions/setup-project
      - name: Test flutter code
        uses: WalterBanda/chapchap-client/.github/actions/test-flutter

  create_build_number:
    name: Create build number by bumping previous build number
    runs-on: ubuntu-latest
    needs: project_setup_testing
    outputs:
      build_number: ${{ steps.get_build_number.outputs.build_number }}
    steps:
      - name: Setup
        uses: WalterBanda/chapchap-client/.github/actions/setup-project
      - name: Bump pubspec yaml
        id: get_build_number
        shell: bash
        run: |
          version=$(grep -m1 version: pubspec.yaml | awk '{print $2}' | tr -d \'\" | cut -d '+' -f1)
          old_version=$(grep -m1 version: pubspec.yaml | awk '{print $2}' | sed 's/ //g;s/'"'"'//g')
          new_build=$(grep -m1 version: pubspec.yaml | awk -F '+' '{if (NF>1) print $NF+1; else print "1"}')
          new_version="$version+$new_build
          new_semver="$version.$new_build
          sed -i "s/$old_version/$new_version/g" pubspec.yaml
          echo "build_number=$new_semver" >> $GITHUB_OUTPUT

      - name: Sync changes to git, publish tags
        shell: bash
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "🔧 Updated build number and project version"
          git tag -a v${{ steps.get_build_number.outputs.build_number }} -m "🚀 Project moving to v${{ steps.get_build_number.outputs.build_number }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

  github_releases:
    needs: create_build_number
    name: Build and Create github releases for android, linux, windows
    uses: "WalterBanda/chapchap-client/.github/workflows/release_github.yml"
    with:
      version: ${{ needs.create_build_number.outputs.build_number }}
    secrets: inherit

  deploy_web_builds:
    needs: create_build_number
    name: Build and Deploy preview web PR builds
    runs-on: ubuntu-latest
    steps:
      - name: Project setup + Flutter SDK setup
        uses: WalterBanda/chapchap-client/.github/actions/setup-project
      - name: Build Preview builds
        uses: WalterBanda/chapchap-client/.github/actions/build/web
      - name: Deploy Preview builds
        uses: WalterBanda/chapchap-client/.github/actions/deploy/web
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHAPCHAP_90547 }}
          production_channel: live
